version = 0.1

[default.deploy.parameters]
stack_name = "ResearchCrawler"
resolve_s3 = true
s3_prefix = "ResearchCrawler"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
